// src/pages/Home.tsx
import { useWebApp } from '@vkruglikov/react-telegram-web-app';

import { useNavigate } from 'react-router-dom'

import { usePostUpscale, usePostGenerate } from '../api'
import { useInit } from '../hooks'
import { useStore } from '../store'

import Header from '../kit/Header'
import Screen from '../kit/Screen'
import New from '../kit/New'

import editAddreplace from '../assets/edit-addreplace.jpg'
import editOutfits from '../assets/edit-outfits.jpg'
import editUpscale from '../assets/edit-upscale.jpg'
import editEraser from '../assets/edit-eraser.jpg'
import editUncrop from '../assets/edit-uncrop.jpg'

import coverAddreplace from '../assets/cover-addreplace.mp4'
import coverEraser from '../assets/cover-eraser.mp4'
import coverGenerate from '../assets/cover-generate.mp4'
import coverOutfits from '../assets/cover-outfits.mp4'
import coverUncrop from '../assets/cover-uncrop.mp4'
import coverUpscale from '../assets/cover-upscale.mp4'

function Home() {
  useInit()
  const WebApp = useWebApp()
  const navigate = useNavigate()

  const { generationId, setPostError } = useStore()

  const postUpscale = usePostUpscale()
  const postGenerate = usePostGenerate()

  const upscale = async () => {
    // todo
    // setIsBusy(true)
    try {
      const resJson = await postUpscale({
        generation_id: generationId || ''
      })
      console.log('postUpscale res', resJson)
      // notificationOccurred('success')
      window.Telegram?.WebApp.close()
      WebApp.close()
    } catch (e) {
      setPostError(e as Error)
    } finally {
      // setIsBusy(false)
    }
  }

  const generate = async () => {
    // setIsBusy(true)
    try {
      const resJson = await postGenerate()
      console.log('postGenerate res', resJson)
      // notificationOccurred('success')
      window.Telegram?.WebApp.close()
      WebApp.close()
    } catch (e) {
      setPostError(e as Error)
    } finally {
      // setIsBusy(false)
    }
  }

  const edits = [
    { title: 'Add&Replace', img: editAddreplace, video: coverAddreplace, path: '/add-replace' },
    { title: 'AI Outfits', img: editOutfits, video: coverOutfits, path: '/outfits', isNew: true },
    { title: 'AI Upscale', img: editUpscale, video: coverUpscale, botCommand: "SELECTED_UPSCALE", callback: upscale },
    { title: 'Eraser', img: editEraser, video: coverEraser, path: '/eraser' },
    { title: 'Uncrop', img: editUncrop, video: coverUncrop, path: '/uncrop' },
    { title: 'Generate image', video: coverGenerate, botCommand: "SELECTED_GENERATE", callback: generate },
  ]

  return (
    <Screen>
      <Header onBack={() => { WebApp.close() }} />

      <div className="max-w-[500px] mx-auto">
        <h4 className="">AI Edits</h4>
        <div className="mt-6 grid grid-cols-2 gap-3">
          {edits.map((item, i) => (
            <button
              key={i}
              className="relative bg-oslo/[0.08] rounded-[12px] bg-cover pb-[109%] bg-center overflow-hidden hover:brightness-110 active:scale-[96%] transition-all"
              // style={{ backgroundImage: `url(${item.img})`}}
              onClick={() => {
                /*
                if (item.botCommand) {
                  WebApp.sendData(item.botCommand)
                  WebApp.close()
                }
                */
                if (item.callback) {
                  item.callback()
                }
                if (item.path) {
                  navigate(item.path)
                }
              }}
            >
              {item.video && (
                <video
                  className="absolute max-w-min w-[102%] min-h-[102%] left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
                  // width="400"
                  // height="300"
                  autoPlay
                  loop
                  muted
                  controls={false}
                  /* poster={item.img} */
                >
                  <source src={item.video} type="video/mp4" />
                </video>
              )}
              {item.isNew && (
                <New />
              )}
              <div className="absolute bottom-0 w-full p-3 pt-5 text-[15px] leading-5 font-semibold text-white bg-gradient-to-b from-transparent to-oslo">
                {item.title}
              </div>
            </button>
          ))}
        </div>
      </div>
    </Screen>
  )
}

export default Home

// src/pages/Home.vue
<script setup lang="ts">
import { inject, ref } from 'vue';

import addReplace from '@/assets/video/cover-addreplace.mp4';
import poster_addReplace from '@/assets/video/cover-addreplace.webp';
import eraser from '@/assets/video/cover-eraser.mp4';
import poster_eraser from '@/assets/video/cover-eraser.webp';
import generate from '@/assets/video/cover-generate.mp4';
import poster_generate from '@/assets/video/cover-generate.webp';
import outfits from '@/assets/video/cover-outfits.mp4';
import poster_outfits from '@/assets/video/cover-outfits.webp';
import uncrop from '@/assets/video/cover-uncrop.mp4';
import poster_uncrop from '@/assets/video/cover-uncrop.webp';
import upscale from '@/assets/video/cover-upscale.mp4';
import poster_upscale from '@/assets/video/cover-upscale.webp';
import { useTelegramSdk } from '@/telegram/use/sdk';
import { SUBMIT_STATE } from '@/tokens';
import { SvgIcon } from '@/ui/SvgIcon';
import { useAlerts } from '@/ui/use/alerts';
import { useApi } from '@/use/useApi';

const sdk = useTelegramSdk();
const alertsService = useAlerts({ autoCloseOnUnmount: true });
const api = useApi();

const submitState = inject(SUBMIT_STATE)!;

const loadingUpscale = ref(false);
const loadingTexttoimg = ref(false);

const features = [
  {
    title: 'Add & Replace',
    video: addReplace,
    path: '/addreplace',
    poster: poster_addReplace,
  },
  {
    title: 'Outfits',
    video: outfits,
    path: '/outfits',
    poster: poster_outfits,
  },
  {
    title: 'Upscale',
    video: upscale,
    path: 'upscale',
    poster: poster_upscale,
  },
  {
    title: 'Eraser',
    video: eraser,
    path: '/eraser',
    poster: poster_eraser,
  },
  {
    title: 'Uncrop',
    video: uncrop,
    path: '/uncrop',
    poster: poster_uncrop,
  },
  {
    title: 'Generate image',
    video: generate,
    path: 'generateimage',
    poster: poster_generate,
  },
];

const onClick = (item: string) => {
  if (item === 'upscale') {
    if (loadingUpscale.value) {
      return;
    }

    loadingUpscale.value = true;

    api.upscale
      .execute({ generation_id: submitState.value!.generation_id as string })
      .then(() => {
        sdk.close();
      })
      .catch(() => {
        alertsService.show('Failed to upscale image. Try again', {
          type: 'error',
        });
      })
      .finally(() => {
        loadingUpscale.value = false;
      });
  } else if (item === 'generateimage') {
    if (loadingTexttoimg.value) {
      return;
    }

    loadingTexttoimg.value = true;

    api.txt2img
      .execute()
      .then(() => {
        sdk.close();
      })
      .catch(() => {
        alertsService.show('Failed to generate image. Try again', {
          type: 'error',
        });
      })
      .finally(() => {
        loadingTexttoimg.value = false;
      });
  }
};
</script>

<template>
  <div :class="$style.wrapper">
    <h3 style="margin-bottom: 0.5rem">AI Tools</h3>

    <div :class="$style.items">
      <component
        v-for="feature in features"
        :key="feature.title"
        :is="feature.path.startsWith('/') ? 'router-link' : 'button'"
        :to="feature.path"
        :class="$style.card"
        @click="onClick(feature.path)"
      >
        <video
          autoplay
          muted
          loop
          playsinline
          preload="auto"
          :poster="feature.poster"
          :class="$style.card__video"
        >
          <source :src="feature.video" type="video/mp4" />
        </video>

        <p :class="$style.card__name">
          {{ feature.title }}
          <svg-icon
            v-if="
              feature.path === 'upscale'
                ? loadingUpscale
                : feature.path === 'generateimage'
                ? loadingTexttoimg
                : false
            "
            name="spinner"
          />
        </p>
      </component>
    </div>
  </div>
</template>

<style module lang="scss">
@import '@/styles/local.scss';

.wrapper {
  padding: 0.5rem;
}

.items {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
}

.card {
  @include clearbutton;
  @include transition(transform);

  position: relative;
  display: block;

  min-width: calc(50% - 0.5rem);
  max-width: calc(50% - 0.5rem);

  aspect-ratio: 1/1.2;
  color: var(--tok-white);
  border-radius: var(--tok-radius-m);
  overflow: hidden;

  cursor: pointer;

  &__video {
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  &__name {
    position: absolute;

    display: flex;
    align-items: center;

    bottom: var(--tok-padding-s);
    left: var(--tok-padding-m);

    font: var(--tok-font-s);
  }

  @include hover {
    transform: scale(1.05);
    opacity: 1;
  }
}
</style>
